import {readFileSync,writeFileSync} from 'node:fs';import {Box3,Vector3,Raycaster,Mesh,Triangle,PerspectiveCamera} from 'three';import{Octree}from'three/examples/jsm/math/Octree.js';import{Capsule}from'three/examples/jsm/math/Capsule.js';import{loadDustGeometryForInspection}from'./scene-geometry';
type Seed={key:string;label:string;regionZh:string;regionEn:string;aliases:string[];material:string;bounds:number[][];feet:number[];focus:number[];description:string};
const root=await loadDustGeometryForInspection();const tree=new Octree().fromGraphNode(root),triangles:Triangle[]=[];root.traverse(o=>{if(!(o instanceof Mesh))return;const g=o.geometry,p=g.attributes.position,i=g.index;for(let n=0;n<(i?i.count:p.count);n+=3){const t=new Triangle();t.a.fromBufferAttribute(p,i?i.getX(n):n).applyMatrix4(o.matrixWorld);t.b.fromBufferAttribute(p,i?i.getX(n+1):n+1).applyMatrix4(o.matrixWorld);t.c.fromBufferAttribute(p,i?i.getX(n+2):n+2).applyMatrix4(o.matrixWorld);triangles.push(t)}});const boxes=triangles.map(t=>new Box3().setFromPoints([t.a,t.b,t.c]));
const vec=(p:number[])=>new Vector3(...p as [number,number,number]),pt=(p:Vector3)=>({x:p.x,y:p.y,z:p.z});const visible=(a:Vector3,b:Vector3)=>new Raycaster(a,b.clone().sub(a).normalize(),0,a.distanceTo(b)-.035).intersectObject(root,true).length===0;
const seeds:Seed[]=JSON.parse(readFileSync('../scene-inspection/dust2_v5_seed_own.json','utf8'));seeds.push(...JSON.parse(readFileSync('../scene-inspection/dust2_v5_seed_other.json','utf8')));
const order=['t-spawn','long-doors','a-pit','a-long','a-site','a-short','xbox','mid-doors','ct-spawn','b-doors','b-site','upper-tunnels','lower-tunnels','outside-tunnels'];seeds.sort((a:Seed,b:Seed)=>order.indexOf(a.key)-order.indexOf(b.key));const anchors=[];
for(const seed of seeds){
 const feet=vec(seed.feet);const hit=new Raycaster(feet.clone().add(new Vector3(0,.6,0)),new Vector3(0,-1,0),0,2).intersectObject(root,true).find(h=>h.face!.normal.clone().transformDirection(h.object.matrixWorld).y>.5);if(hit)feet.y=hit.point.y+.022;
 const capsule=new Capsule(feet.clone().add(new Vector3(0,.28,0)),feet.clone().add(new Vector3(0,1.4,0)),.28),collision=tree.capsuleIntersect(capsule);if(collision&&collision.depth>.03)throw new Error('BAD_FEET '+seed.key+' '+collision.depth);
 const eye=feet.clone().add(new Vector3(0,1.6,0)),focus=vec(seed.focus),featureBox=new Box3(vec(seed.bounds[0]),vec(seed.bounds[1])),direction=focus.clone().sub(feet);direction.y=0;direction.normalize();const side=new Vector3(direction.z,0,-direction.x),size=new Vector3(1.2,1.3,1.1),half=size.clone().multiplyScalar(.5);let chosen:{center:Vector3;target:Vector3}|null=null;let bestOverlap=Infinity;
 search:for(const lateral of [1.3,-1.3,1.7,-1.7,2.1,-2.1,2.5,-2.5,.9,-.9,0])for(const distance of [1.8,2.2,1.4,2.6,3.2,3.8,4.4])for(const height of [.95,1.3,1.7,2.1,2.5]){
 const center=feet.clone().addScaledVector(direction,distance).addScaledVector(side,lateral);center.y=feet.y+height;const box=new Box3(center.clone().sub(half),center.clone().add(half));if(triangles.some((t,i)=>box.intersectsBox(boxes[i])&&box.intersectsTriangle(t)))continue;
 const corners=[];for(const x of [-1,0,1])for(const y of [-1,0,1])for(const z of [-1,0,1])corners.push(center.clone().add(new Vector3(x*half.x,y*half.y,z*half.z)));if(corners.some(c=>!visible(eye,c)))continue;
 const target=focus.clone().lerp(center,.26),camera=new PerspectiveCamera(70,4/3,.05,500);camera.position.copy(eye);camera.lookAt(target);camera.updateMatrixWorld();const fs=[];for(const x of [featureBox.min.x,featureBox.max.x])for(const y of [featureBox.min.y,featureBox.max.y])for(const z of [featureBox.min.z,featureBox.max.z])fs.push(new Vector3(x,y,z));if([...corners,...fs].some(p=>{const q=p.clone().project(camera);return Math.abs(q.x)>.95||Math.abs(q.y)>.95||q.z<0||q.z>1}))continue;
 const projectBounds=(ps:Vector3[])=>{const qs=ps.map(p=>p.clone().project(camera));return [Math.min(...qs.map(q=>q.x)),Math.min(...qs.map(q=>q.y)),Math.max(...qs.map(q=>q.x)),Math.max(...qs.map(q=>q.y))]};const f=projectBounds(fs),v=projectBounds(corners);const overlap=Math.max(0,Math.min(f[2],v[2])-Math.max(f[0],v[0]))*Math.max(0,Math.min(f[3],v[3])-Math.max(f[1],v[1]))/((f[2]-f[0])*(f[3]-f[1]));if(overlap<bestOverlap){chosen={center,target};bestOverlap=overlap;}if(overlap===0)break search;
 }
 console.log('CUE_OVERLAP',seed.key,bestOverlap);if(!chosen)throw new Error('NO_CUE '+seed.key);
 const id='dust2v5-'+seed.key,index=anchors.length+1;anchors.push({id,locusId:'L'+String(index).padStart(2,'0'),label:seed.label,routeOrder:index,zone:seed.regionZh,position:pt(focus),calloutAliases:seed.aliases,playerCallout:{regionZh:seed.regionZh,regionEn:seed.regionEn,aliases:seed.aliases,landmarkZh:seed.label.split('·')[1],confidence:'geometry-and-classic-layout',evidence:'Original GLB material/component bounds; classic-map regional layout; physical-landmark suffix is descriptive, not a claimed canonical special callout.'},landmark:{description:seed.description,shape:seed.description,material:'原模型石墙、木箱、木门与绿箱',colors:['砂岩棕','木棕'],visibleFeatures:[seed.description],focusPoint:pt(focus),framingBounds:{min:pt(featureBox.min),max:pt(featureBox.max),evidence:'Original normalized GLB '+seed.material+' physical feature bounds.'}},semanticTags:[seed.regionZh,seed.regionEn,...seed.aliases],affordances:['在地标前线索区排列','在地标旁线索区环绕'],capacity:3,approach:{position:pt(feet),eye:pt(eye),lookAt:pt(chosen.target),yaw:Math.atan2(eye.x-chosen.target.x,eye.z-chosen.target.z),pitch:Math.atan2(chosen.target.y-eye.y,Math.hypot(eye.x-chosen.target.x,eye.z-chosen.target.z))},cueVolume:{id:id+'-cue',center:pt(chosen.center),size:pt(size),allowedRelations:['在线索区按顺序排列','在线索区环形环绕','在线索区被框住','在线索区周期起伏'],allowedRelationIds:['ordered-row','orbit','frame','rise'],maxObjects:3},neighbors:[],relativeObjects:[{name:seed.regionEn,relation:'玩家区域名；点位后缀描述原模型中的具体物件'}],verification:{method:'blender-raycast',reachable:null,visible:null,sceneVersion:'dust2-vrchris-08f7ab9c-v5',evidence:'Restored candidate; fresh geometry/controller acceptance pending. Browser gameplay unverified.'}});
}
for(let i=0;i<anchors.length;i++)anchors[i].neighbors=[anchors[i-1]?.id,anchors[i+1]?.id].filter(Boolean) as never[];
writeFileSync('src/lib/dust2CalloutAnchors.json',JSON.stringify(anchors,null,2));writeFileSync('../scene-inspection/dust2_v5_anchors.json',JSON.stringify(anchors,null,2));console.log('WROTE',anchors.length);
